name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  deploy:
    # Only run if the CI workflow succeeded
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    env:
      DRY_RUN: true  # <-- Set to "false" to actually deploy

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Docker Compose App
        run: |
          if [ "$DRY_RUN" = "true" ]; then
            echo "[DRY RUN] Deployment skipped."
            echo "Would run: az webapp create --resource-group drone-explorer-rg --plan drone-explorer-plan --name drone-explorer-webapp --multicontainer-config-type compose --multicontainer-config-file docker-compose.yml"
          else
            az webapp create \
              --resource-group drone-explorer-rg \
              --plan drone-explorer-plan \
              --name drone-explorer-webapp \
              --multicontainer-config-type compose \
              --multicontainer-config-file docker-compose.yml
